# SPDX-License-Identifier: Apache-2.0

name: golangci-lint

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3
        with:
          go-version: 1.19
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@23faadfdeb23a6f9e511beaba149bb123b5b145a # v3
        with:
          version: v1.50.1
          args: --timeout=10m
