# SPDX-License-Identifier: Apache-2.0

name: test

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v3
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3
        with:
          go-version: 1.19
          check-latest: true

      - run: go test -v ./...
