# SPDX-License-Identifier: Apache-2.0

name: test

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3
        with:
          go-version: 1.19
          check-latest: true

      - run: go test -v ./...
